### PR TITLE
Fixes ordering-dependent issue with Slider (closes #93)

### LINKED ISSUE #93: Wrongly rounded value when creating a Slider
```javascript
var slider = new photonui.Slider({
    value: 0.5,
    min: 0, max: 10,
    step: 0.5,          
    decimalDigits: 2,
});

photonui.domInsert(slider, "demo");
```

## Expected result

A new slider with current value set to 0.5.

## Result

A new slider with current value set to 1.0.

## Note

Moving the value parameter to the end of the object make it work.

### PR DESCRIPTION
**Pull request by flozz**

### CODE REVIEW

File: src/interactive/slider.js [hunk 1]
```diff
@@ -53,6 +53,18 @@ var Slider = NumericField.$extend({
     __init__: function (params) {
         this.$super(params);
 
+        if (params && params.decimalDigits === undefined) {
+            this.decimalDigits = 0;
+        }
+
+        if (params && params.min === undefined) {
+            this.decimalDigits = 0;
```
Comment (Breush) [inline src/interactive/slider.js]: this.min = 0 ?

File: src/interactive/slider.js [hunk 2]
```diff
@@ -53,6 +53,18 @@ var Slider = NumericField.$extend({
...
+        }
+
+        if (params && params.max === undefined) {
+            this.decimalDigits = 100;
```
Comment (Breush) [inline src/interactive/slider.js]: this.max = 100 ?

**Comment by Bazard** [comment]
Tested and approved !
